# Generated by Django 3.1.2 on 2020-10-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20190802_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(max_length=1000)),
                ('new_text', models.TextField(max_length=1000)),
                ('original_text_length', models.IntegerField(max_length=1000)),
                ('new_text_length', models.IntegerField(max_length=1000)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
