# Generated by Django 3.1.2 on 2020-10-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_textmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmodel',
            name='new_text_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='original_text_length',
            field=models.IntegerField(),
        ),
    ]
