# Generated by Django 3.1.2 on 2020-11-20 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20201029_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textmodel',
            old_name='new_text_length',
            new_name='category_id',
        ),
        migrations.RemoveField(
            model_name='textmodel',
            name='new_text',
        ),
        migrations.RemoveField(
            model_name='textmodel',
            name='original_text',
        ),
        migrations.RemoveField(
            model_name='textmodel',
            name='original_text_length',
        ),
    ]
