# Generated by Django 3.1.2 on 2020-12-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20201120_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemodel',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='category_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='filemodel',
            table='file_box',
        ),
    ]
